"""
backend/vision_intelligence/schemas/vision.py
Pydantic Schemas for Vision Intelligence Pipeline.
"""

from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field

try:
    # Pydantic v2
    from pydantic import field_validator
    
    def validate_confidence_range(v: int) -> int:
        if not (0 <= v <= 100):
            raise ValueError("Confidence score must be an integer between 0 and 100")
        return v

    V2_VALIDATOR = True
except ImportError:
    # Pydantic v1 fallback
    from pydantic import validator
    V2_VALIDATOR = False


class SeverityLevel(str, Enum):
    """Enumeration of issue visual severity levels."""
    CRITICAL = "Critical"
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"


class UrgencyLevel(str, Enum):
    """Enumeration of recommended action urgency levels."""
    IMMEDIATE = "Immediate Action Required"
    HIGH = "High Priority"
    STANDARD = "Standard Repair"
    ROUTINE = "Routine Maintenance"


class VisionAnalysisRequest(BaseModel):
    """Incoming request model for vision analysis."""
    image_base64: Optional[str] = Field(
        default=None,
        description="Base64 encoded string representation of the uploaded image asset"
    )
    image_url: Optional[str] = Field(
        default=None,
        description="Direct HTTP/HTTPS URL pointing to hosted image asset"
    )
    stream_thoughts: bool = Field(
        default=True,
        description="Whether to stream intermediate visual inspection steps via Server-Sent Events"
    )


class VisionAnalysisResponse(BaseModel):
    """Output payload generated by Stage 1 Vision Intelligence Engine."""
    thinking_steps: List[str] = Field(
        ...,
        description="Sequential list of AI visual inspection traces",
        json_schema_extra={
            "example": [
                "Scanning visual scene background...",
                "Detected dark standing water with foam on tarmac.",
                "Evaluating severity: High traffic risk detected."
            ]
        } if hasattr(BaseModel, "model_config") else None
    )
    is_civic_issue: bool = Field(
        ...,
        description="Flag indicating whether a valid civic/infrastructure issue was identified",
        json_schema_extra={"example": True}
    )
    issue_type: str = Field(
        ...,
        description="Classified civic problem category",
        json_schema_extra={"example": "Drainage Overflow"}
    )
    severity: SeverityLevel = Field(
        ...,
        description="Evaluated urgency and visual severity level",
        json_schema_extra={"example": SeverityLevel.HIGH}
    )
    confidence: int = Field(
        ...,
        ge=0,
        le=100,
        description="Confidence score percentage integer between 0 and 100",
        json_schema_extra={"example": 94}
    )
    description: str = Field(
        ...,
        description="Objective description of visual evidence captured in photo",
        json_schema_extra={"example": "Raw sewage and dark wastewater overflowing from an open drain cover onto a two-lane asphalt road."}
    )
    affected_infrastructure: str = Field(
        ...,
        description="Primary impacted public asset or municipal infrastructure",
        json_schema_extra={"example": "Asphalt Roadway and Stormwater Drainage System"}
    )
    visible_risks: List[str] = Field(
        ...,
        description="List of immediate or potential secondary public safety hazards",
        json_schema_extra={"example": ["Traffic Impairment", "Pedestrian Slip Hazard", "Vector-borne Disease Spread"]}
    )
    estimated_urgency: UrgencyLevel = Field(
        ...,
        description="Recommended action response urgency classification",
        json_schema_extra={"example": UrgencyLevel.HIGH}
    )
    image_quality_notes: str = Field(
        default="Clear",
        description="Quality assessment of input photo capture",
        json_schema_extra={"example": "Clear outdoor daylight capture"}
    )

    if V2_VALIDATOR:
        @field_validator("confidence")
        @classmethod
        def check_confidence(cls, v: int) -> int:
            return validate_confidence_range(v)
    else:
        @validator("confidence")
        def check_confidence(cls, v: int) -> int:
            if not (0 <= v <= 100):
                raise ValueError("Confidence score must be an integer between 0 and 100")
            return v
